services:
  federation-registry-feeder:
    image: harbor.cloud.infn.it/datacloud-middleware/federation-registry-feeder
    container_name: feeder
    environment:
      - PROVIDERS_CONF_DIR=/providers-conf
    env_file:
      - ../.env
    volumes:
      - ../providers-conf:/providers-conf:ro
      - ../certs:/certs:ro
    # Infinite loop to keep container live doing nothing
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"
 